import { AlertCircle,Building2,CalendarClock,TrendingUp } from "lucide-react";
import { PageHeader } from "@/components/layout";
import { ErrorState,MetricCard,Skeleton } from "@/components/ui";
import { AttentionRequired } from "@/features/dashboard/components/AttentionRequired";
import { ProjectHealthTable } from "@/features/dashboard/components/ProjectHealthTable";
import { SiteToday } from "@/features/dashboard/components/SiteToday";
import { attentionItems,siteSnapshot } from "@/features/dashboard/data/dashboard.mock";
import { useProjects } from "@/features/projects/hooks/useProjects";
export function DashboardPage(){const {data:projects=[],isLoading,isError,refetch}=useProjects();if(isLoading)return <div className="dashboard-loading"><Skeleton/><Skeleton/><Skeleton/><Skeleton/></div>;if(isError)return <ErrorState title="Unable to load dashboard" description="Portfolio information could not be retrieved." onRetry={()=>void refetch()}/>;const active=projects.filter(project=>project.status==="active");const average=active.length?Math.round(active.reduce((sum,project)=>sum+project.progress,0)/active.length):0;const upcoming=projects.filter(project=>project.status!=="completed"&&project.status!=="cancelled").length;return <><PageHeader title="Dashboard" description="Portfolio performance, operational exceptions and items requiring attention."/><section className="metrics"><MetricCard label="Active projects" value={active.length} detail={`${projects.length} total projects`} icon={<Building2 size={19}/>}/><MetricCard label="Average progress" value={`${average}%`} detail="Across active projects" icon={<TrendingUp size={19}/>}/><MetricCard label="Attention items" value={attentionItems.length} detail="Requires review" icon={<AlertCircle size={19}/>}/><MetricCard label="Projects in delivery" value={upcoming} detail="Not completed or cancelled" icon={<CalendarClock size={19}/>}/></section><div className="dashboard-primary"><AttentionRequired items={attentionItems}/><SiteToday items={siteSnapshot}/></div><ProjectHealthTable projects={projects}/></>}
