import { BarChart3,CircleDot,Sparkles } from "lucide-react";
import { useLocation } from "react-router-dom";
import { StatusBadge } from "@/components/ui";

type Tone="neutral"|"info"|"success"|"warning"|"danger";
type Config={summary:string;progress:[string,number,string];stats:[string,string,string][];focus:[string,string,Tone][]};

const data:Record<string,Config>={
dashboard:{summary:"Portfolio control room for delivery, exceptions and site activity across active construction projects.",progress:["Portfolio delivery confidence",74,"Stable with schedule attention required"],stats:[["Active projects","2","Both in delivery"],["Portfolio progress","55%","Weighted demo progress"],["Open attention","5","2 high-priority"]],focus:[["RFIs requiring response","3","warning"],["Pending inspections","2","info"],["Schedule variance","-6%","danger"]]},
projects:{summary:"Executive project register showing portfolio status, delivery progress and management ownership.",progress:["Portfolio completion",55,"Combined progress across current projects"],stats:[["Total projects","2","Demo portfolio"],["In construction","2","100% active"],["Planned completions","2","Within 2027"]],focus:[["Commercial Building","68%","success"],["Infrastructure Works","42%","info"],["Portfolio health","Watch","warning"]]},
overview:{summary:"Single-project command view combining progress, responsibilities, delivery dates and current project health.",progress:["Overall project progress",68,"Target this period: 71%"],stats:[["Physical progress","68%","3% behind target"],["Open actions","14","5 due this week"],["Work packages","24","18 currently active"]],focus:[["Structural works","72%","success"],["Architectural works","58%","info"],["MEP works","44%","warning"]]},
search:{summary:"Project-wide discovery surface for quickly finding records across commercial, technical and site modules.",progress:["Indexed project records",92,"Demo search coverage across modules"],stats:[["Indexed records","486","Across 20 record types"],["Open records","84","Searchable by status"],["Linked records","312","Cross-module references"]],focus:[["Drawings","86","info"],["Documents","112","neutral"],["Site controls","74","success"]]},
notifications:{summary:"Action-oriented project inbox for assignments, workflow events, due dates and critical alerts.",progress:["Notification clearance",64,"Unread items reduced during the current period"],stats:[["Unread","9","3 need action"],["Critical","2","Immediate review"],["Due today","4","Assigned workflows"]],focus:[["Critical safety alert","1","danger"],["RFI responses due","3","warning"],["Approvals received","6","success"]]},
audit:{summary:"Traceable activity history showing who changed what, when it changed and where the event originated.",progress:["Traceability coverage",100,"All demo mutations represented"],stats:[["Audit events","286","Current project"],["Active actors","18","Users and integrations"],["Changed records","143","Unique entities"]],focus:[["User changes","214","info"],["Workflow events","58","neutral"],["Integration events","14","success"]]},
users:{summary:"Project membership and role-based authorization for contractor, consultant and client-side users.",progress:["Access review completion",88,"Quarterly project access review"],stats:[["Project users","18","Across 7 roles"],["Active","16","2 invitations pending"],["Privileged roles","5","Management access"]],focus:[["Project managers","2","info"],["Document control","3","neutral"],["Pending invites","2","warning"]]},
wbs:{summary:"Hierarchical work breakdown structure connecting scope, progress, ownership and downstream controls.",progress:["Scope progress",64,"Weighted progress across current WBS packages"],stats:[["WBS items","24","5 top-level packages"],["Active packages","18","Current execution scope"],["Completed","4","2 not started"]],focus:[["Structure","72%","success"],["Architecture","58%","info"],["MEP","44%","warning"]]},
schedule:{summary:"Planning view for activity dates, current progress, late work and upcoming delivery milestones.",progress:["Schedule performance",82,"Demo SPI equivalent: 0.94"],stats:[["Activities","36","Across active work fronts"],["Late activities","3","Recovery needed"],["Next milestone","14d","Level 1 completion"]],focus:[["On track","27","success"],["At risk","6","warning"],["Late","3","danger"]]},
activities:{summary:"Execution register for planned construction activities, priorities, responsibility and measurable progress.",progress:["Activity completion",61,"Average progress of current demo activities"],stats:[["Active","18","Across all disciplines"],["High priority","7","Management focus"],["Completed this week","5","Accepted progress"]],focus:[["Structural frame","72%","success"],["Internal blockwork","58%","info"],["AC ducting","44%","warning"]]},
"daily-progress":{summary:"Site diary capturing daily production, weather, workforce, equipment, delays and remarks.",progress:["Daily plan achieved",86,"Production versus planned daily output"],stats:[["Manpower","184","People on site"],["Equipment","27","Active plant"],["Activities worked","9","Across 6 work fronts"]],focus:[["Weather","Clear · 36°C","info"],["Safety events","0 LTI","success"],["Constraints","2","warning"]]},
attachments:{summary:"Field evidence gallery for site photos, supporting documents and files linked to controlled records.",progress:["Records with evidence",78,"Demo attachment coverage"],stats:[["Site photos","126","Tagged by location"],["Documents","38","Supporting files"],["Added today","14","Latest field evidence"]],focus:[["Quality evidence","46","info"],["Safety evidence","31","warning"],["Progress photos","87","success"]]},
manpower:{summary:"Daily labor-control view by contractor, trade, category, hours and workforce deployment.",progress:["Planned workforce coverage",92,"184 actual versus 200 planned"],stats:[["Total workforce","184","Current day"],["Skilled labor","138","75% of workforce"],["Overtime","196h","Current reporting day"]],focus:[["Carpentry","46","info"],["Masonry","54","success"],["HVAC","38","warning"]]},
equipment:{summary:"Plant and equipment register highlighting utilization, availability, maintenance and field location.",progress:["Fleet availability",89,"24 of 27 units available or in use"],stats:[["Active equipment","27","On project"],["In use","21","78% utilization"],["Maintenance due","3","Within 7 days"]],focus:[["In use","21","success"],["Available","3","info"],["Maintenance","3","warning"]]},
materials:{summary:"Material-control view for required, ordered, delivered and consumed quantities with inspection status.",progress:["Material readiness",76,"Weighted delivery against current requirements"],stats:[["Material lines","42","Controlled items"],["Delivered","76%","Against ordered quantity"],["Inspection pending","4","Awaiting acceptance"]],focus:[["Concrete","71%","success"],["Rebar","93%","success"],["Gypsum board","29%","warning"]]},
procurement:{summary:"Procurement pipeline showing RFQ, evaluation, order placement, delivery progress and required-by dates.",progress:["Procurement readiness",72,"Critical packages weighted by required date"],stats:[["Open packages","18","Across procurement stages"],["Committed value","AED 4.8M","Current orders"],["Critical items","3","Required within 14 days"]],focus:[["Ordered","9","success"],["Evaluation","5","info"],["RFQ / delayed","4","warning"]]},
subcontractors:{summary:"Package-level subcontract management for scope, commercial value, progress and delivery performance.",progress:["Subcontract progress",53,"Weighted across active subcontract packages"],stats:[["Packages","8","6 currently active"],["Awarded value","AED 18.4M","Demo package value"],["Avg. rating","3.8/5","Performance score"]],focus:[["Structural Works","68%","success"],["Architectural","42%","info"],["MEP Systems","39%","warning"]]},
variations:{summary:"Change-control register for instructions, quotations, approvals and commercial impact against baseline.",progress:["Variation closure",58,"Approved or closed changes versus total raised"],stats:[["Variations","12","Current register"],["Approved","AED 152K","Approved exposure"],["Pending","AED 418K","Awaiting decision"]],focus:[["Approved","4","success"],["Under review","5","warning"],["Rejected / closed","3","neutral"]]},
documents:{summary:"Controlled document register covering submissions, revisions, transmittals, responses and review status.",progress:["Document response performance",84,"Responses within target review period"],stats:[["Documents","112","Current register"],["Under review","18","Consultant action"],["Overdue responses","4","Needs follow-up"]],focus:[["Approved","71","success"],["Under review","18","info"],["Overdue","4","danger"]]},
drawings:{summary:"Drawing register organized around discipline, revision control, submission status, location and response.",progress:["Drawing approval",79,"Latest revisions approved or approved with comments"],stats:[["Drawings","86","Current revisions"],["Approved","68","Including comments"],["Coordination","11","MEP / architectural"]],focus:[["Architectural","32","info"],["Structural","21","success"],["MEP","33","warning"]]},
rfis:{summary:"Technical query workflow for questions, assignments, response dates and cost or schedule impact.",progress:["RFI response performance",81,"Answered within target response period"],stats:[["Open RFIs","7","Current outstanding"],["Overdue","2","Past response date"],["Impact flagged","4","Cost or schedule"]],focus:[["Critical","1","danger"],["High priority","3","warning"],["Answered this week","6","success"]]},
inspections:{summary:"Inspection workflow for WIRs and MIRs with requested dates, results and corrective actions.",progress:["First-time pass rate",88,"Accepted inspections without rework"],stats:[["Scheduled","6","Next 7 days"],["Passed","24","Current period"],["Failed","2","Corrective action required"]],focus:[["Work inspections","18","info"],["Material inspections","8","neutral"],["Corrective actions","2","danger"]]},
quality:{summary:"Quality-control register for NCRs, observations, corrective actions, verification and closeout.",progress:["Quality closeout",73,"Closed or verified quality records"],stats:[["Open NCRs","5","2 major"],["Observations","9","Active follow-up"],["Closed this month","14","Verified records"]],focus:[["Major NCR","2","danger"],["Verification","4","warning"],["Closed","14","success"]]},
safety:{summary:"HSE operational view for observations, near misses, incidents, toolbox talks and corrective actions.",progress:["Safety action closure",91,"Actions closed within target period"],stats:[["LTI free","248d","Demo safety streak"],["Open actions","5","No critical incidents"],["Toolbox talks","24","Current month"]],focus:[["High observations","1","warning"],["Near misses","1","info"],["Lost-time incidents","0","success"]]},
issues:{summary:"Cross-functional issue and action register connecting technical, quality, safety, schedule and commercial constraints.",progress:["Issue resolution",67,"Closed actions against raised actions"],stats:[["Open issues","14","Across project functions"],["High priority","6","Management attention"],["Actions due","8","Next 7 days"]],focus:[["Coordination","5","warning"],["Quality","4","info"],["Safety","2","danger"]]},
reports:{summary:"Controlled reporting library for weekly, monthly, quality, safety and management reports.",progress:["Reporting compliance",96,"Reports issued to planned calendar"],stats:[["Reports","18","Current project library"],["Issued","15","Controlled revisions"],["In preparation","3","Current reporting cycle"]],focus:[["Weekly progress","8","success"],["Monthly progress","6","info"],["Functional reports","4","neutral"]]},
analytics:{summary:"Cross-functional management analytics combining progress, cost, quality, safety, RFIs and unresolved exposure.",progress:["Overall project health",77,"Composite demo indicator for design review"],stats:[["Physical progress","58.0%","Average activity progress"],["Cost variance","AED 268K","Budget less forecast"],["Open controls","29","RFI, quality, safety, issues"]],focus:[["Schedule","Watch","warning"],["Commercial","Stable","success"],["Quality / HSE","Controlled","info"]]},
costs:{summary:"Cost-control register for budget, commitments, actuals, forecast and variance by cost code and WBS.",progress:["Budget utilization",62,"Actual cost against current demo budget"],stats:[["Budget","AED 15.0M","Current cost baseline"],["Committed","AED 14.3M","95% committed"],["Forecast","AED 14.7M","AED 268K under budget"]],focus:[["Structural","AED 4.95M","success"],["Architectural","AED 3.38M","info"],["MEP","AED 6.25M","warning"]]}
};

function key(pathname:string){if(pathname==="/")return"dashboard";if(pathname==="/projects")return"projects";const p=pathname.split("/").filter(Boolean);return p[0]==="projects"&&p.length>=3?p[2]:"";}

export function PageShowcase(){
  const item=data[key(useLocation().pathname)];
  if(!item)return null;
  return <section className="page-showcase" aria-label="Demo design data">
    <div className="page-showcase-main">
      <div className="page-showcase-kicker"><Sparkles size={14}/><span>Demo data</span></div>
      <p>{item.summary}</p>
      <div className="page-showcase-stats">{item.stats.map(([label,value,detail])=><div className="page-showcase-stat" key={label}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>)}</div>
      <div className="page-showcase-progress"><div><span><BarChart3 size={15}/>{item.progress[0]}</span><strong>{item.progress[1]}%</strong></div><div className="page-showcase-track"><span style={{width:item.progress[1]+"%"}}/></div><small>{item.progress[2]}</small></div>
    </div>
    <aside className="page-showcase-focus">
      <div className="page-showcase-focus-title"><CircleDot size={15}/><strong>Current focus</strong></div>
      {item.focus.map(([label,value,tone])=><div className="page-showcase-focus-row" key={label}><span>{label}</span><StatusBadge tone={tone}>{value}</StatusBadge></div>)}
      <p>Sample operational data is intentionally shown so the page design can be reviewed before backend integration.</p>
    </aside>
  </section>;
}
