import { createBrowserRouter } from "react-router-dom";
import { AppShell } from "@/components/layout/AppShell";
import { DashboardPage } from "@/features/dashboard/pages/DashboardPage";
import { ProjectsPage } from "@/features/projects/pages/ProjectsPage";
import { ProjectDetailsPage } from "@/features/projects/pages/ProjectDetailsPage";
import { ModulePlaceholderPage } from "@/features/shared/pages/ModulePlaceholderPage";
import { NotFoundPage } from "@/features/shared/pages/NotFoundPage";
const modules=[["schedule","Schedule","Plan milestones, dependencies, baselines and project dates."],["activities","Activities","Manage work packages, activities, tasks and execution progress."],["daily-progress","Daily Progress","Capture daily site progress, resources, delays, inspections and remarks."],["manpower","Manpower","Track project workforce by contractor, trade and date."],["equipment","Equipment","Manage equipment utilization, status, breakdowns and maintenance."],["materials","Materials","Track material requirements, deliveries, consumption and inspection status."],["procurement","Procurement","Manage requisitions, quotations, purchase orders and deliveries."],["costs","Costs","Monitor contract values, commitments, actual costs and forecasts."],["documents","Documents","Control project documents, submissions, revisions and approvals."],["rfis","RFIs","Track requests for information, responses and overdue actions."],["inspections","Inspections","Manage inspection requests, results and supporting records."],["quality","Quality","Manage NCRs, observations and corrective actions."],["safety","Safety","Track observations, incidents, permits and corrective actions."]] as const;
export const router=createBrowserRouter([{path:"/",element:<AppShell/>,children:[{index:true,element:<DashboardPage/>},{path:"projects",element:<ProjectsPage/>},{path:"projects/:projectId",element:<ProjectDetailsPage/>},...modules.map(([path,title,description])=>({path,element:<ModulePlaceholderPage title={title} description={description}/>})),{path:"*",element:<NotFoundPage/>}]}]);
