import { Navigate,createBrowserRouter } from "react-router-dom";
import { AppShell } from "@/components/layout/AppShell";
import { DashboardPage } from "@/features/dashboard/pages/DashboardPage";
import { ActivitiesPage } from "@/features/activities/pages/ActivitiesPage";
import { SchedulePage } from "@/features/schedule/pages/SchedulePage";
import { DailyProgressPage } from "@/features/daily-progress/pages/DailyProgressPage";
import { ManpowerPage } from "@/features/manpower/pages/ManpowerPage";
import { EquipmentPage } from "@/features/equipment/pages/EquipmentPage";
import { MaterialsPage } from "@/features/materials/pages/MaterialsPage";
import { ProcurementPage } from "@/features/procurement/pages/ProcurementPage";
import { SubcontractorsPage } from "@/features/subcontractors/pages/SubcontractorsPage";
import { VariationsPage } from "@/features/variations/pages/VariationsPage";
import { CostsPage } from "@/features/costs/pages/CostsPage";
import { DocumentsPage } from "@/features/documents/pages/DocumentsPage";
import { DrawingsPage } from "@/features/drawings/pages/DrawingsPage";
import { ProjectWorkspace } from "@/features/projects/components/ProjectWorkspace";
import { ProjectDetailsPage } from "@/features/projects/pages/ProjectDetailsPage";
import { ProjectModulePage } from "@/features/projects/pages/ProjectModulePage";
import { ProjectsPage } from "@/features/projects/pages/ProjectsPage";
import { ModulePlaceholderPage } from "@/features/shared/pages/ModulePlaceholderPage";
import { NotFoundPage } from "@/features/shared/pages/NotFoundPage";
import { WbsPage } from "@/features/wbs/pages/WbsPage";
const modules=[["schedule","Schedule","Plan milestones, dependencies, baselines and project dates."],["activities","Activities","Manage work packages, activities, tasks and execution progress."],["daily-progress","Daily Progress","Capture daily site progress, resources, delays, inspections and remarks."],["manpower","Manpower","Track project workforce by contractor, trade and date."],["equipment","Equipment","Manage equipment utilization, status, breakdowns and maintenance."],["materials","Materials","Track material requirements, deliveries, consumption and inspection status."],["procurement","Procurement","Manage requisitions, quotations, purchase orders and deliveries."],["subcontractors","Subcontractors","Manage subcontract packages, scope, commitments and performance."],["variations","Variations","Control scope changes, cost and time impacts, and approvals."],["costs","Costs","Monitor contract values, commitments, actual costs and forecasts."],["documents","Documents","Control project documents, submissions, revisions and approvals."],["drawings","Drawings","Control design, shop, coordination and as-built drawing revisions."],["rfis","RFIs","Track requests for information, responses and overdue actions."],["inspections","Inspections","Manage inspection requests, results and supporting records."],["quality","Quality","Manage NCRs, observations and corrective actions."],["safety","Safety","Track observations, incidents, permits and corrective actions."]] as const;
export const router=createBrowserRouter([{path:"/",element:<AppShell/>,children:[{index:true,element:<DashboardPage/>},{path:"projects",element:<ProjectsPage/>},{path:"projects/:projectId",element:<ProjectWorkspace/>,children:[{index:true,element:<Navigate to="overview" replace/>},{path:"overview",element:<ProjectDetailsPage/>},{path:"wbs",element:<WbsPage/>},{path:"schedule",element:<SchedulePage/>},{path:"activities",element:<ActivitiesPage/>},{path:"daily-progress",element:<DailyProgressPage/>},{path:"manpower",element:<ManpowerPage/>},{path:"equipment",element:<EquipmentPage/>},{path:"materials",element:<MaterialsPage/>},{path:"procurement",element:<ProcurementPage/>},{path:"subcontractors",element:<SubcontractorsPage/>},{path:"variations",element:<VariationsPage/>},{path:"costs",element:<CostsPage/>},{path:"documents",element:<DocumentsPage/>},{path:"drawings",element:<DrawingsPage/>},...modules.filter(([path])=>path!=="activities"&&path!=="schedule"&&path!=="daily-progress"&&path!=="manpower"&&path!=="equipment"&&path!=="materials"&&path!=="procurement"&&path!=="subcontractors"&&path!=="variations"&&path!=="costs"&&path!=="documents"&&path!=="drawings").map(([path,title,description])=>({path,element:<ProjectModulePage title={title} description={description}/>}))]},...modules.map(([path,title,description])=>({path,element:<ModulePlaceholderPage title={title} description={description}/>})),{path:"*",element:<NotFoundPage/>}]}]);
