import { cloneElement,isValidElement,useEffect,useId,useRef,useState,type KeyboardEvent,type ReactElement,type ReactNode } from "react";
export function Dropdown({trigger,children,align="end"}:{trigger:ReactNode;children:ReactNode;align?:"start"|"end"}){
  const [open,setOpen]=useState(false),id=useId(),root=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(!open)return;const outside=(e:MouseEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false)};document.addEventListener("mousedown",outside);return()=>document.removeEventListener("mousedown",outside)},[open]);
  const triggerNode=isValidElement(trigger)?cloneElement(trigger as ReactElement<Record<string,unknown>>,{"aria-haspopup":"menu","aria-expanded":open,"aria-controls":id,onClick:()=>setOpen(v=>!v)}):<button type="button" aria-haspopup="menu" aria-expanded={open} aria-controls={id} onClick={()=>setOpen(v=>!v)}>{trigger}</button>;
  const key=(e:KeyboardEvent<HTMLDivElement>)=>{if(e.key==="Escape"){setOpen(false);return}const items=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('[role="menuitem"]'));const index=items.indexOf(document.activeElement as HTMLElement);if(e.key==="ArrowDown"){e.preventDefault();items[(index+1+items.length)%items.length]?.focus()}if(e.key==="ArrowUp"){e.preventDefault();items[(index-1+items.length)%items.length]?.focus()}};
  return <div className="relative inline-block" ref={root}>{triggerNode}{open&&<div id={id} className={`absolute z-60 mt-1.5 min-w-45 rounded-xl border border-slate-200 bg-white p-1.5 shadow-xl dark:border-slate-700 dark:bg-slate-900 ${align==="end"?"right-0":"left-0"}`} role="menu" onKeyDown={key} onClick={()=>setOpen(false)}>{children}</div>}</div>;
}
export function DropdownItem({children,onClick}:{children:ReactNode;onClick?:()=>void}){return <button type="button" className="w-full rounded-lg px-2.5 py-2 text-left text-sm text-slate-700 transition hover:bg-slate-100 focus:bg-slate-100 focus:outline-none dark:text-slate-200 dark:hover:bg-slate-800 dark:focus:bg-slate-800" role="menuitem" onClick={onClick}>{children}</button>}
